version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
      java: corretto17
    commands:
      - echo "Installing dependencies..."
      - npm install --prefix frontend
      
  build:
    commands:
      - echo "Building projects..."
      - npm run build --prefix frontend
      - cd backend && chmod +x ./gradlew && ./gradlew clean build -x test && cd ..
      
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      
      - echo "Building Docker images..."
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-backend-repo:latest ./backend
      - docker build -t $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-frontend-repo:latest ./frontend
      
  post_build:
    commands:
      - echo "Pushing Docker images to ECR..."
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-backend-repo:latest
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-frontend-repo:latest
      
      - echo "Updating EKS cluster config..."
      - aws eks update-kubeconfig --name my-team-cluster --region $AWS_REGION
      
      - echo "Deploying to EKS..."
      - kubectl set image deployment/backend-deployment backend=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-backend-repo:latest
      - kubectl set image deployment/frontend-deployment frontend=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/my-frontend-repo:latest
      - echo "Deployment completed!"

artifacts:
  files:
    - '**/*' # 배포 후 로그 확인 등을 위해 루트 전체 아카이브