server:
  port: 8080 # 백엔드 서버의 기본 포트번호입니다.

spring:
  datasource:
    # [엔드포인트] 부분에 방금 받은 주소를 넣으세요
    url: jdbc:mysql://mini161-db.cdqdyxhthgdx.us-west-1.rds.amazonaws.com:3306/bookdb?useSSL=false&serverTimezone=UTC
    username: user161
    password: Aivler161!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update # 처음 연결 시 테이블이 없으면 자동으로 만들어줍니다. (매우 편리!)
    show-sql: true

  sql:
    init:
      mode: always # data.sql을 항상 실행해서 시드 데이터를 자동 삽입합니다.
      encoding: UTF-8 # Windows에서 한글이 깨지지 않도록 UTF-8 명시